# Test Windows bash
name: Test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: bash-windows-test 
        shell: bash 
        run: | 
          mkdir -p temp/temp2
          curl https://google.com
          bash --version
          jq --version
          openssl version 
