# Test Windows bash
name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: bash-windows-test 
        shell: bash 
        run: |
          mkdir -p temp/temp2
          curl https://google.com
	  bash --version
	  jq --version
	  curl -L -s https://github.com/ajshastri/chocolatey-packages/blob/e558ba4cb5d2602163af16a4b224dad143170859/scripts/zulu-sync.sh | bash
